# -*- mode: ruby -*-
# vi: set ft=ruby :

# Configuration variables
# These value can be changed to scale the cluster or adjust resources

NUM_WORKERS = 2              # Number of worker nodes (change to scale cluster)
CONTROLLER_MEMORY = 4096     # Controller RAM in MB (4GB)
CONTROLLER_CPUS = 2          # Controller CPU cores
WORKER_MEMORY = 6144         # Worker RAM in MB (6GB)
WORKER_CPUS = 2              # Worker CPU cores


# Network configuration (easily change IPs here!)
CONTROL_IP = "192.168.56.100"
WORKER_IP_BASE = "192.168.56"
WORKER_IP_START = 101

# Vagrant configuration
# This block configures all VMs for the Kubernetes cluster

Vagrant.configure("2") do |config|
  # Shared storage for all VMs
  config.vm.synced_folder "./shared", "/mnt/shared"
  
  # Controller VM (ctrl)
  
  config.vm.define "ctrl" do |ctrl|
    # Use Ubuntu 24.04 as base operating system
    ctrl.vm.box = "bento/ubuntu-24.04"
    ctrl.vm.hostname = "ctrl"

    # Add private network with fixed IP
    ctrl.vm.network "private_network", ip: CONTROL_IP
    
    # VirtualBox-specific configuration
    ctrl.vm.provider "virtualbox" do |vb|
      vb.name = "k8s-ctrl"                # Name shown in VirtualBox GUI
      vb.memory = CONTROLLER_MEMORY       # Allocate RAM
      vb.cpus = CONTROLLER_CPUS           # Allocate CPU cores
    end

    # Ansible provisioning for controller
    ctrl.vm.provision "ansible" do |ansible|
      ansible.playbook = "playbooks/general.yaml"
      ansible.extra_vars = {
        num_workers: NUM_WORKERS,
        control_ip: CONTROL_IP,
        worker_ip_base: WORKER_IP_BASE,
        worker_ip_start: WORKER_IP_START
      }
    end
    ctrl.vm.provision "ansible" do |ansible|
      ansible.playbook = "playbooks/ctrl.yaml"
    end

  end
  
  # Worker VMs (node-1, node-2, ...)

  # This loop creates NUM_WORKERS worker VMs automatically
  (1..NUM_WORKERS).each do |i|
    # Define worker VM with sequential numbering (node-1, node-2, etc.)
    config.vm.define "node-#{i}" do |node|
      node.vm.box = "bento/ubuntu-24.04"
      
      # Set hostname with number (node-1, node-2, etc.)
      node.vm.hostname = "node-#{i}"
      
      # Add private network with sequential IPs (192.168.56.101, 102, etc.)
      node.vm.network "private_network", ip: "#{WORKER_IP_BASE}.#{WORKER_IP_START + i - 1}"

      # VirtualBox-specific configuration
      node.vm.provider "virtualbox" do |vb|
        vb.name = "k8s-node-#{i}"
        vb.memory = WORKER_MEMORY
        vb.cpus = WORKER_CPUS
      end

      # Ansible provisioning for workers
      node.vm.provision "ansible" do |ansible|
        ansible.playbook = "playbooks/general.yaml"
        ansible.extra_vars = {
          num_workers: NUM_WORKERS,
          control_ip: CONTROL_IP,
          worker_ip_base: WORKER_IP_BASE,
          worker_ip_start: WORKER_IP_START
        }
      end
      node.vm.provision "ansible" do |ansible|
        ansible.playbook = "playbooks/node.yaml"
      end
    end
  end

  # Auto-generate inventory.cfg
  config.trigger.after :up, :provision do |trigger|
    trigger.name = "Generate inventory.cfg"
    trigger.ruby do |env, machine|
      # Only generate after last VM is up (avoid multiple writes)
      if machine.name.to_s == "node-#{NUM_WORKERS}"
        
        inventory_content = <<~INVENTORY
          # Auto-generated by Vagrant
          # Generated: #{Time.now}
          
          [control]
          ctrl ansible_host=#{CONTROL_IP} ansible_user=vagrant ansible_ssh_private_key_file=~/.ssh/id_ed25519

          [workers]
        INVENTORY
        
        # Add workers dynamically
        (1..NUM_WORKERS).each do |i|
          inventory_content += "node-#{i} ansible_host=#{WORKER_IP_BASE}.#{WORKER_IP_START + i - 1} ansible_user=vagrant ansible_ssh_private_key_file=~/.ssh/id_ed25519\n"
        end
        
        inventory_content += <<~INVENTORY

          [k8s:children]
          control
          workers
        INVENTORY
        
        # Write to playbooks/inventory.cfg
        File.write("playbooks/inventory.cfg", inventory_content)
        puts "Generated playbooks/inventory.cfg with #{NUM_WORKERS} workers"
      end
    end
  end

end
