apiVersion: v2
name: sms-checker
description: SMS Span Detection Application - Kubernetes Deployment 
type: application
version: 1.0.0
appVersion: "1.0"

maintainers:
  - name: DODA Team 9

keywords:
  - sms
  - spam-detection
  - machine-learning

home: https://github.com/doda25-team9/operation

