apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.service.name }}
  labels:
    app: {{ .Values.app.labels.app }}
    component: {{ .Values.app.labels.component }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
spec:
  selector:
    app: {{ .Values.app.labels.app }}
    component: {{ .Values.app.labels.component }}
  ports:
    - port: {{ .Values.app.service.port }}
      targetPort: {{ .Values.app.service.port }}
      protocol: TCP
      name: http
  type: {{ .Values.app.service.type }}