{{- if .Values.istio.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{ .Values.istio.gateway.name }}
  labels:
    app: {{ .Values.app.labels.app }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
spec:
  selector:
    istio: {{ .Values.istio.gateway.ingressGatewaySelector }}
  
  servers:
  - port:
      number: 80      
      name: http
      protocol: HTTP
    hosts:
    - "{{ .Values.istio.host }}"
    - "*.{{ .Values.istio.host }}"
    - "{{ .Values.istio.stableHost }}"
    - "{{ .Values.istio.canaryHost }}"
{{- end }}