{{- if .Values.istio.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: app-destinationrule
  labels:
    app: {{ .Values.app.labels.app }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
spec:
  host: {{ .Values.app.service.name }}
  
  trafficPolicy:
    {{- if .Values.istio.stickySession.enabled }}
    loadBalancer:
      consistentHash:
        httpCookie:
          name: {{ .Values.istio.stickySession.cookieName }}
          ttl: {{ .Values.istio.stickySession.ttl }}s
    {{- end }}

    connectionPool:
      tcp:
        maxConnections: 100
      http:
        http1MaxPendingRequests: 50
        http2MaxRequests: 100
    
    outlierDetection:
      consecutive5xxErrors: 5
      interval: 30s
      baseEjectionTime: 30s
      maxEjectionPercent: 50
  
  subsets:
  - name: v1
    labels:
      version: v1 

  - name: v2
    labels:
      version: v2 
{{- end }}