apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  labels:
    app: {{ .Values.app.labels.app }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
type: Opaque
stringData:
  # Override during install:
  #   helm install sms-checker ./helm-chart \
  #     --set secret.smtpUser=real@email.com \
  #     --set secret.smtpPass=realpassword
  SMTP_USER: {{ .Values.secret.smtpUser | quote }}
  SMTP_PASS: {{ .Values.secret.smtpPass | quote }}